#!/usr/bin/env python3
#
# Create the gallery html page from the list of images found in img/
# using the database artworks.csv
#

from dataclasses import dataclass
from datetime import date
from typing import Any, Dict, List, Optional, TextIO, Tuple
import argparse
import csv
import json
import html
import math
import os
import re
import subprocess

ALL_PATH = '/all'
IMG_PATH = '/img'
CSS_PATH = '/css'
SERIES_PATH = '/series'
ART_PATH = '/art'

@dataclass
class Page:
    title: str
    # Folder containing the md and html files
    folder: str
    # Output file
    html_file: str
    # page-specific HTML data to insert at the beginning of the page
    page_specific_html: str
    # CSV rows of artworks to display
    rows: List[Dict[str, str]]

# The built-in '.capitalize()' method will downcase the rest of the string,
# which we don't want.
def capitalize_first_char(s: str) -> str:
    if len(s) > 0:
        return s[0].upper() + s[1:]
    else:
        return s

# Zero-width matching just before a letter that should be capitalized
# according to English usage.
# This works only for standard English letters a-z.
WORD_START_RE = r"(?:^|(?<=\s))(?=[a-z])"

# Because '.title()' does a shit job.
#
# This capitalizes too much. Capitalization rules for English require
# distinguishing nouns from other words, which requires a dictionary.
# Let's not use this function.
def capitalize_all_words(s: str) -> str:
    return "".join([ capitalize_first_char(word)
                     for word in re.split(WORD_START_RE, s) ])

def capitalize_fr(s: str) -> str:
    return capitalize_first_char(s)

def capitalize_en(s: str) -> str:
    return capitalize_first_char(s)

# Uses 'identify' from ImageMagick
def image_dimensions(image_filename: str) -> Tuple[int, int]:
    p = subprocess.run([
        "identify",
        "-format",
        '{"width":%[fx:w], "height":%[fx:h]}',
        image_filename
    ], capture_output=True)
    dic = json.loads(p.stdout.decode())
    return (dic['width'], dic['height'])

def figure_scaling(image_filename: str) -> float:
    (width, height) = image_dimensions(image_filename)
    aspect_ratio = float(width) / float(height)
    # sqrt(2) is the aspect ratio of A5, A4, A3, etc.
    max_aspect_ratio = math.sqrt(2.)
    if aspect_ratio >= max_aspect_ratio:
        return 1.0
    else:
        return math.sqrt(aspect_ratio / max_aspect_ratio)

def needs_rebuild(src: str, dst: str) -> bool:
    return not os.path.isfile(dst) \
        or os.path.getmtime(dst) < os.path.getmtime(src)

def inches_to_cm(x: float) -> float:
    return 2.54 * x

def format_dimensions(row: Dict[str, str]) -> Optional[str]:
    width_cm = -1.0
    height_cm = -1.0
    if row['width_in'] and row['height_in']:
        width_cm = inches_to_cm(float(row['width_in']))
        height_cm = inches_to_cm(float(row['height_in']))
    if row['width_cm'] and row['height_cm']:
        width_cm = float(row['width_cm'])
        height_cm = float(row['height_cm'])
    if width_cm > 0:
        return f"{width_cm:.1f} cm × {height_cm:.1f} cm"
    else:
        return None

def format_support(row: Dict[str, str]) -> Optional[str]:
    support = row['support']
    if support:
        return support
    else:
        return None

def format_location(row: Dict[str, str]) -> Optional[str]:
    poss = row['possessor_kind']
    if poss == 'private' or poss == 'family':
        return 'Private collection'
    elif poss == 'ephemeral' or poss == 'recycled':
        return 'Ephemeral'
    else:
        return None

def verbose_command(argv: List[str]) -> None:
    print(f"{' '.join(argv)}")
    subprocess.run(argv)

def get_title(row: Dict[str, str]) -> str:
    title_en = capitalize_en(row['title_en'])
    title_fr = capitalize_fr(row['title_fr'])
    title_lang = row['title_lang']
    title1 = None
    title2 = None
    if title_lang == "en":
        title1 = title_en
        title2 = title_fr
    elif title_lang == "fr":
        title1 = title_fr
        title2 = title_en
    elif title_lang:
        raise Exception(f"Unsupported language '{title_lang}' in row {row}")
    if title1:
        title = title1
        if title2 and title2 != title1:
            title = f"{title} ({title2})"
        return title
    else:
        return 'Untitled'


def get_img_page_url(row: Dict[str, str]) -> str:
    return f"{ART_PATH}/{row['artwork_id']}"


# 2022-09-08 -> September 2022
def reformat_date(isodate: str) -> str:
    date_ = date.fromisoformat(isodate)
    return f"{date_.strftime('%B')} {date_.year}"


def make_standalone_page(row: Dict[str, str]) -> None:
    artwork_id = row['artwork_id']
    img_id = row['image_id']
    date_str = reformat_date(row['date'])
    title = get_title(row)
    img_name = img_id + '.jpg'
    hash_name = img_id

    img_url = IMG_PATH + '/large/' + img_name
    html_dir = 'art/' + artwork_id
    html_file = html_dir + '/index.html'
    os.makedirs(html_dir, exist_ok=True)

    # URL to this artwork on the gallery listing
    gallery_url = f"{ALL_PATH}#{hash_name}"

    main_caption = f"{title}"
    main_caption_html = f"""
<div>
  {html.escape(main_caption)}
</div>
"""

    dimensions = format_dimensions(row)
    support = format_support(row)
    location = format_location(row)
    dim_html = ""
    if dimensions:
        line = dimensions
        if support:
            line += f", {support}"
        dim_html = f"""
<div style='font-size: 80%'>{html.escape(line)}</div>
"""

    author_html = f"""
<div class="main_caption">
  Martin Jambon, {date_str}
  <a href="https://www.instagram.com/martinjambon/">
    <img src="{IMG_PATH}/other/instagram-logo.png"
        title="Instagram"
        style="height:1em;padding:0em 0.5em;vertical-align:middle;opacity:0.5">
  </a>
</div>
"""

    loc_html = ""
    if location:
        loc_html = f"""
<div style='font-style: italic'>{html.escape(location)}</div>
"""

    page_contents = f"""
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name=viewport content="width=device-width, initial-scale=1">
  <title>{html.escape(title)}</title>
  <link rel="stylesheet" href="{CSS_PATH}/generic.css" />
  <style type="text/css">
    body {{
      background-color: white;
      font-family: sans-serif;
    }}

    div.center {{
      max-width: 80%;
      max-height: 60%;

      position: fixed;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;

      margin: auto;
      text-align: center;
    }}

    img.artwork {{
      max-height: 100%;
      max-width: 100%;
      object-fit: contain;
      text-align: left;
    }}

    .caption {{
      display: inline-block;
      width: 70%;

      margin: 3em 0em;
      color: grey;
    }}

    a {{
      color: inherit;
      text-decoration: none;
    }}
  </style>
</head>
<body>
  <div class="center">
    <img class="artwork" src="{img_url}"/>
    <div class="caption">
      <a href="{html.escape(gallery_url)}"
         title="view in gallery">
        {main_caption_html}{author_html}
        <div style="margin:1em 0em">
          {dim_html}{loc_html}
        </div>
      </a>
    </div>
  </div>
</body>
</html>
"""
    with open(html_file, "w") as out:
        out.write(page_contents)


# Print an artwork on a page showing a series.
def print_series_row(row: Dict[str, str],
              html_file: TextIO,
              generate_dependencies: bool = False,
              force: bool = False) -> None:
    img_id = row['image_id']
    date_str = reformat_date(row['date'])
    title = get_title(row)
    img_name = img_id + '.jpg'
    hash_name = img_id

    medium = 'img/medium/' + img_name
    if generate_dependencies:
        make_standalone_page(row)

        # Generate images of different sizes
        orig = 'img/original/' + img_name

        large = 'img/large/' + img_name
        # JPEG image quality. Default quality is 92, max is 100.
        quality = "95"
        if force or needs_rebuild(orig, large):
            verbose_command(["convert", "-resize", "1600x1600",
                             "-quality", quality,
                             orig, large])

        if force or needs_rebuild(orig, medium):
            verbose_command(["convert", "-resize", "800x800",
                             "-quality", quality,
                             orig, medium])

        # Padded square images for Instagram
        square = 'img/square/' + img_name
        if force or needs_rebuild(orig, square):
            verbose_command([
                "convert",
                orig,
                "-resize", "1450x1450>",
                "-background", "#eee",
                "-gravity", "center",
                "-extent", "1600x1600",
                "-quality", quality,
                square
            ])

    # This resizes the image on the page so that all images have the same
    # surface area. (except for those which are too wide, which will be
    # rendered with a smaller surface area)
    fig_margin = int((1.0 - figure_scaling(medium)) / 2 * 100)

    medium_img_url = IMG_PATH + '/medium/' + img_name

    main_caption = f"{title}"
    # Fragile: pandoc really wants to insert <p> elements but we're trying
    # to avoid that. The backslash below disables the insertion of <p>.
    main_caption_html = f"""
<div class="main_caption">
  {html.escape(main_caption)}
  <a href="#{html.escape(hash_name)}"
     title="Direct link to artwork"
     class="hash_link">#</a>\
</div>
"""

    dimensions = format_dimensions(row)
    support = format_support(row)
    location = format_location(row)
    dim_html = ""
    if dimensions:
        line = dimensions
        if support:
            line += f", {support}"
        dim_html = f"""
<div style='font-size: 80%'>{html.escape(line)}</div>
"""

    author_html = f"""
<div class="main_caption">\
  Martin Jambon, {date_str}\
  <a href="https://www.instagram.com/martinjambon/">
    <img src="{IMG_PATH}/other/instagram-logo.png"
         title="Instagram"
         style="height:1em;padding:0em 0.5em;vertical-align:middle;opacity:0.6"/>
  </a>
</div>
"""

    loc_html = ""
    if location:
        loc_html = f"""
<div style='font-style: italic'>{html.escape(location)}</div>\
"""

    # Write to main page
    img_page_url = get_img_page_url(row)
    html_file.write(
f"""
<a name="{html.escape(hash_name)}">
<figure style="margin: 0px {fig_margin}%; padding-top: 40px">
  <a href="{html.escape(img_page_url)}">
    <img src="{html.escape(medium_img_url)}"
         alt="abstract art"
         class="artwork"/>
  </a>
  <figcaption>
    {main_caption_html}{author_html}
    <div style="margin:0.5em 0em">{dim_html}{loc_html}</div>
  </figcaption>
</figure>
"""
    )


def generate_series(
        page: Page,
        generate_dependencies: bool,
        force: bool = False) -> None:
    print(f"### Generating {page.html_file}")
    rows = page.rows
    with open(page.html_file, 'w') as out:
        out.write(
        f"""
<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>
  <meta charset="utf-8" />
  <meta name=viewport content="width=device-width, initial-scale=1">
  <title>{html.escape(page.title)}</title>
  <link rel="stylesheet" href="{CSS_PATH}/generic.css" />
  <style type="text/css">
/*
   Hide the site-wide navigation bar to avoid confusing the user
   who only cares about the art stuff.
*/
.navbar {{
  display: none;
}}

/* Override site-wide style */
body {{
  font-family: sans-serif;
}}

/* Override text color for text and links */
body, a, a:active, a:visited {{
  color: #999;
}}

/* Disable zoom-in on hover on touchscreens */
@media (hover: hover) {{
  .artworks:hover img.artwork {{
    opacity: 0.2;
  }}

  .artworks:hover img.artwork:hover {{
    opacity: 1.0;

    /* place the image in the foreground when zooming in */
    z-index: 1;
  }}

  img.artwork:hover {{
    /* zoom on hover */
    transform: scale(1.6);
  }}

  img.artwork {{
    transition: transform .2s;
  }}
}}

img.artwork {{
  /* grey frame around each artwork image */
  background-color:#eee;
  padding: 3%;
  width: 94%;

  position: relative;
  z-index: 0;
}}

figcaption {{
  margin: 1em 0em;
}}

.hash_link {{
  visibility: hidden;
}}

/* Make the hash-link only visible when hovering over the title. */
.main_caption:hover .hash_link {{
  visibility: visible;
  color: #999;
}}
  </style>
</head>
<body>
<h1>{html.escape(page.title)}</h1>
<div class="artworks">
"""
    )
        for row in rows:
            if row['show'] == '1':
                print_series_row(row, out, generate_dependencies, force=force)
        out.write(
        """
</div>
<p class="discreet" style="margin:4em 0em">
  All artworks on <a href="https://martinj.art/">martinj.art</a>
  ©&nbsp;2022&ndash;2023
  by <a href="https://mjambon.com">Martin Jambon</a>
  are licensed under
  <a href="http://creativecommons.org/licenses/by-nc-nd/4.0/">CC&nbsp;BY-NC-ND&nbsp;4.0</a>
  unless stated otherwise.
</p>
"""
        )


# Print what represents a series on the main page.
def print_main_row(
        html_file: TextIO,
        series_url: str,
        img_id: str,
        title: str) -> None:
    img_name = f'{img_id}.jpg'
    img_url = f'{IMG_PATH}/medium/{img_name}'

    medium = f'img/medium/{img_name}'
    # This resizes the image on the page so that all images have the same
    # surface area. (except for those which are too wide, which will be
    # rendered with a smaller surface area)
    fig_margin = int((1.0 - figure_scaling(medium)) / 2 * 100)

    # no whitespace between inline blocks to avoid undesirable spacing
    row_html = f"""\
<a href="{html.escape(series_url)}"
   class="series_link">\
<div class="box">
  <div class="shadowbox"></div>
  <div class="textbox">{html.escape(title)}</div>
  <img class="artwork" src="{html.escape(img_url)}"/>
</div>\
</a>\
"""
    # Write to main page
    html_file.write(row_html)


def generate_main(
        html_file: str,
        artwork_rows: List[Dict[str, str]],
        series_rows: List[Dict[str, str]],
        force: bool = False) -> None:
    print(f"### Generating {html_file}")
    with open(html_file, 'w') as out:
        out.write(
        f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name=viewport content="width=device-width, initial-scale=1">
  <title>Art by Martin Jambon</title>
  <link rel="stylesheet" href="{CSS_PATH}/generic.css" />
  <style type="text/css">
body {{
  margin: 6.5em auto 2.5em auto;
  padding: 0.5em 1.5em;
  max-width: 100ex;
  font-family: sans-serif;
}}

body, a, a:active, a:visited {{
  color: #999;
}}

@media (hover: hover) {{
  .shadowbox {{
    position: absolute;

    /* fade in and out */
    visibility: hidden;
    opacity: 0;
    transition: 0.3s;

    width: 100%;
    height: 100%;
    z-index: 1;
    background-color: rgba(0, 0, 0, 0.4);
  }}

  .box:hover .shadowbox {{
    visibility: visible;
    opacity: 1;
  }}

  .textbox {{
    /* fade in and out */
    opacity: 0.8;
    transition: 0.3s;
  }}

  .box:hover .textbox {{
    opacity: 1;
  }}
}}

.contents {{
  margin-top: 6ex;
  flex-wrap: wrap;
  line-height: 0;
  text-align: center;
}}

.box {{
  position: relative;
  display: inline-block;
  width: 25ex;
  height: 25ex;
  overflow: hidden;
  text-align: left;
}}

.textbox {{
  color: white;
  font-size: 120%;
  font-weight: bold;
  line-height: normal;

  /* center */
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);

  /* show text over the image on mobile devices */
  z-index: 2;
}}

.series_link, .series_link:hover {{
  text-decoration: none;
}}

img.artwork {{
  position: relative;
  height: 100%;
  width: 100%;
  object-fit: cover;
  transform: scale(1.6);
}}
</style>
<h1>Hello.</h1>
<p>
I am Martin Jambon. This is the online collection of all my artworks.
</p>
<p>
Follow me on <a href="https://www.instagram.com/martinjambon">Instagram</a>
or email me at <a href="mailto:contact@martinj.art">contact@martinj.art</a>.
</p>
<div class="contents">
"""
    )

        latest_img_id = artwork_rows[0]['image_id']
        print_main_row(
            html_file=out,
            series_url=ALL_PATH,
            img_id=latest_img_id,
            title='Latest'
        )
        for row in series_rows:
            series_id = row['series_id']
            series_url = f'{SERIES_PATH}/{series_id}'
            img_id = row['image_id']
            title = row['short_description_en']
            print_main_row(
                html_file=out,
                series_url=series_url,
                img_id=img_id,
                title=title
            )
        # Hack: fillers that allow the images in the last visible row to
        # be left-aligned rather than centered.
        for i in range(3):
            out.write('<div class="box" style="height:0"></div>')

        out.write(
        """
</div>
"""
        )


def load_artworks_csv() -> List[Dict[str, str]]:
    with open('artworks.csv', 'r') as csvfile:
        row_reader = csv.DictReader(csvfile)
        return list(row_reader)


def load_series_csv() -> List[Dict[str, str]]:
    with open('series.csv', 'r') as csvfile:
        row_reader = csv.DictReader(csvfile)
        return list(row_reader)


# Group artworks by series ID
def extract_series(series_rows: List[Dict[str, str]],
                   artwork_rows: List[Dict[str, str]]) -> List[Page]:
    series_tbl = { row['series_id']:row for row in series_rows }
    artwork_groups: Dict[str, List[Dict[str,str]]] = {}
    for row in artwork_rows:
        key = row['series']
        if not key:
            key = 'other'
        if key:
            if key in artwork_groups:
                artwork_groups[key].append(row)
            else:
                artwork_groups[key] = [row]
    def create_page(series_id: str, rows: List[Dict[str,str]]) -> Page:
        title = series_tbl[series_id]['short_description_en'];
        os.makedirs(f'series/{series_id}', exist_ok=True)
        return Page(
            title=title,
            folder=f'series/{series_id}',
            html_file=f'series/{series_id}/index.html',
            page_specific_html='',
            rows=rows
        )
    return [ create_page(series_id, rows)
             for series_id, rows in artwork_groups.items() ]


def main() -> None:
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('--force', action='store_true',
                    help='resize all images rather than being lazy about it')
    args = parser.parse_args()

    os.makedirs('img/large', exist_ok=True)
    os.makedirs('img/medium', exist_ok=True)

    artwork_rows = load_artworks_csv()
    series_rows = load_series_csv()

    # All artworks
    os.makedirs('all', exist_ok=True)
    page_all = Page(
        title='All Artworks!',
        folder='all',
        html_file='all/index.html',
        page_specific_html='This is everything.',
        rows=artwork_rows
    )
    generate_series(page_all, generate_dependencies=True, force=args.force)

    # Series
    os.makedirs('series', exist_ok=True)
    series_pages = extract_series(series_rows, artwork_rows)
    for page in series_pages:
        generate_series(page, generate_dependencies=False, force=args.force)

    # Main page
    generate_main('index.html', artwork_rows, series_rows, force=args.force)

main()
